sylius_resource:
    resources:
        app.menu:
            driver: doctrine/orm
            classes:
                model: App\Entity\Menu\Menu
                repository: App\Repository\Menu\MenuRepository
                form: App\Form\Type\MenuType
        app.menu_page:
            driver: doctrine/orm
            classes:
                model: App\Entity\Menu\MenuPage
                repository: App\Repository\Menu\MenuPageRepository
                form: App\Form\Type\MenuPageType
        app.menu_item:
            driver: doctrine/orm
            classes:
                model: App\Entity\Menu\MenuItem
                repository: App\Repository\Menu\MenuItemRepository
                form: App\Form\Type\MenuItemType
        app.page_menu_image:
            driver: doctrine/orm
            classes:
                model: App\Entity\Menu\MenuPageImage
                repository: App\Repository\Menu\MenuPageImageRepository
                form: App\Form\Type\MenuItemType

        app.category_promotion:
            driver: doctrine/orm
            classes:
                model: App\Entity\CategoryPromotion\CategoryPromotion
                repository: App\Repository\CategoryPromotion\CategoryPromotionRepository
                form: App\Form\Type\CategoryPromotionType
            translation:
                classes:
                    model: App\Entity\CategoryPromotion\CategoryPromotionTranslation
                    form: App\Form\Type\CategoryPromotionTranslationType

        app.category_promotion_image:
            driver: doctrine/orm            
            classes:
                model: App\Entity\CategoryPromotion\CategoryPromotionImage
                form: App\Form\Type\CategoryPromotionImageType

        app.category_outfit:
            driver: doctrine/orm            
            classes:
                model: App\Entity\CategoryOutfit\CategoryOutfit
                repository: App\Repository\CategoryOutfit\CategoryOutfitRepository
                form: App\Form\Type\CategoryOutfitType
            translation:
                classes:
                    model: App\Entity\CategoryOutfit\CategoryOutfitTranslation
                    form: App\Form\Type\CategoryOutfitType

        app.category_outfit_image:
            driver: doctrine/orm            
            classes:
                model: App\Entity\CategoryOutfit\CategoryOutfitImage
                form: App\Form\Type\CategoryOutfitImageType
