sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"

# app_admin_menu:
#     resource: |
#         alias: app.menu
#         section: admin
#         templates: "@SyliusAdmin\\Crud"
#         redirect: update
#         grid: app_admin_menu
#         vars:
#             all:
#                 subheader: app.ui.menus_subheader
#             index:
#                 icon: 'file image outline'
#     type: sylius.resource
#     prefix: /admin

# app_admin_menu_page:
#     resource: |
#         alias: app.menu_page
#         section: admin
#         templates: "@SyliusAdmin\\Crud"
#         redirect: update
#         grid: app_admin_menu_page
#         vars:
#             all:
#                 subheader: app.ui.menu_pages_subheader
#                 templates:
#                     form: "menu/menuPage.html.twig"
#             index:
#                 icon: 'file image outline'
#     type: sylius.resource
#     prefix: /admin

# app_admin_menu_item:
#     resource: |
#         alias: app.menu_item
#         section: admin
#         templates: "@SyliusAdmin\\Crud"
#         redirect: update
#         grid: app_admin_menu_item
#         vars:
#             all:
#                 subheader: app.ui.menu_items_subheader
#             index:
#                 icon: 'file image outline'
#     type: sylius.resource
#     prefix: /admin

app_admin_category_promotion:
    resource: |
        alias: app.category_promotion
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: app_admin_category_promotion
        vars:
            all:
                subheader: app.ui.category_promotions_subheader
                templates: 
                    form: "categoryPromotion/categoryPromotionTranslation.html.twig"
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: /admin
app_admin_category_outfit:
    resource: |
        alias: app.category_outfit
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: app_admin_category_outfit
        vars:
            all:
                subheader: app.ui.category_outfits_subheader
                templates: 
                    form: "categoryOutfit/categoryOutfitTranslation.html.twig"
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: /admin
app_admin_product_feature:
    resource: |
        alias: app.product_feature
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: app_admin_product_feature
        vars:
            all:
                subheader: app.ui.product_features_subheader
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: /admin
    
app_admin_translation_override_dictionary:
    resource: |
        alias: app.translation_override_dictionary
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: app_admin_translation_override_dictionary
        vars:
            all:
                subheader: app.ui.translation_override_dictionaries_subheader
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: /admin

app_admin_product_description_template:
    resource: |
        alias: app.product_description_template
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: app_admin_product_description_template
        vars:
            all:
                subheader: app.ui.product_description_template_subheader
                templates: 
                    form: "product/productDescriptionTemplate.html.twig"
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: /admin
