sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"

app:
    resource: ../src/Controller/
    type: annotation
    
app_admin_category_promotion:
    resource: |
        alias: app.category_promotion
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: app_admin_category_promotion
        vars:
            all:
                subheader: app.ui.category_promotions_subheader
                templates: 
                    form: "categoryPromotion/categoryPromotionTranslation.html.twig"
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: /admin
app_admin_category_outfit:
    resource: |
        alias: app.category_outfit
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: app_admin_category_outfit
        vars:
            all:
                subheader: app.ui.category_outfits_subheader
                templates: 
                    form: "categoryOutfit/categoryOutfitTranslation.html.twig"
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: /admin
app_admin_product_feature:
    resource: |
        alias: app.product_feature
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: app_admin_product_feature
        vars:
            all:
                subheader: app.ui.product_features_subheader
                templates: 
                    form: "product/product_feature.html.twig"
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: /admin
    
app_admin_translation_override_dictionary:
    resource: |
        alias: app.translation_override_dictionary
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: app_admin_translation_override_dictionary
        vars:
            all:
                subheader: app.ui.translation_override_dictionaries_subheader
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: /admin

app_admin_product_description_template:
    resource: |
        alias: app.product_description_template
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: app_admin_product_description_template
        vars:
            all:
                subheader: app.ui.product_description_template_subheader
                templates: 
                    form: "product/productDescriptionTemplate.html.twig"
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: /admin
