'App\Entity\Menu\Menu':
    collectionOperations:
        get:
            method: 'GET'
            path: '/menus/{localeIso}'
            controller: 'App\Controller\ApiMenuController::getMenus'
            normalization_context:
                groups: ['menu:read']
'App\Entity\Taxonomy\Taxon':
    collectionOperations:
        get:
            method: 'GET'
            path: '/taxons/{slug}/{localeIso}'
            controller: 'App\Controller\ApiTaxonController::getTaxons'
            normalization_context:
                groups: ['taxon:read']
