'MonsieurBiz\SyliusMenuPlugin\Entity\Menu':
    collectionOperations:
        get:
            method: 'GET'
            path: '/shop/menus/{localeIso}'
            controller: 'App\Controller\ApiMenuController::getMenus'
            normalization_context:
                groups: ['menu:read']
'App\Entity\Taxonomy\Taxon':
    collectionOperations:
        get:
            method: 'GET'
            path: '/shop/taxons/{code}/{localeIso}'
            controller: 'App\Controller\ApiTaxonController::getTaxons'
            normalization_context:
                groups: ['taxon:read']
