'App\Entity\Menu\Menu':
    collectionOperations:
        get:
            method: 'GET'
            path: '/menus/{localeIso}'
            controller: 'App\Controller\ApiMenuController::getMenus'
            normalization_context:
                groups: ['menu:read']
