'MonsieurBiz\SyliusMenuPlugin\Entity\Menu':
    collectionOperations:
        get:
            method: 'GET'
            path: '/shop/menus/{localeIso}'
            controller: 'App\Controller\ApiMenuController::getMenus'
            normalization_context:
                groups: ['menu:read']
'App\Entity\Taxonomy\Taxon':
    collectionOperations:
        get:
            method: 'GET'
            path: '/shop/taxons/{code}/{localeIso}'
            controller: 'App\Controller\ApiTaxonController::getTaxons'
            normalization_context:
                groups: ['taxon:read']
'App\Entity\Product\ProductDescriptionBlockContent':
    collectionOperations:
        get:
            method: 'GET'
            path: '/shop/product/{productId}/description/{localeIso}'
            controller: 'App\Controller\ApiProductController::getProductDescription'
            normalization_context:
                groups: ['product:read']
'App\Entity\Product\ProductFeature':
    collectionOperations:
        get:
            method: 'GET'
            path: '/shop/product/{productId}/features/{localeIso}'
            controller: 'App\Controller\ApiProductController::getProductFeatures'
            normalization_context:
                groups: ['product:read']
'App\Entity\Product\ProductAttribute':
    itemOperations:
        get:
            method: 'GET'
            path: '/shop/product/{productId}/attribute/image'
            controller: 'App\Controller\ApiProductController::getAttributeImage'
