services:
  php:
    build: php
    depends_on:
      - mysql
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=EDITME
      - DATABASE_URL=mysql://sylius:nopassword@mysql/sylius
      - MAILER_URL=smtp://localhost
      - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
    volumes:
      - ../:/srv/sylius:rw,cached
      - ../public:/srv/sylius/public:rw,delegated
      - ../public/media:/srv/sylius/public/media:rw

  mysql:
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-nopassword}
      - MYSQL_DATABASE=sylius
      - MYSQL_USER=sylius
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nopassword}
    volumes:
      - ./mysql/data:/var/lib/mysql:rw,delegated
    ports:
      - "3306:3306"

  nodejs:
    build: nodejs
    depends_on:
      - php
    environment:
      - GULP_ENV=dev
      - PHP_HOST=php
      - PHP_PORT=9000
    volumes:
      - ../:/srv/sylius:rw,cached
      - ../public:/srv/sylius/public:rw,delegated
    ports:
      - "35729:35729"

  nginx:
    build: nginx
    depends_on:
      - php
      - nodejs
    volumes:
      - ../public:/srv/sylius/public:ro
      - ../public/media:/srv/sylius/public/media:ro
    ports:
      - "80:80"

  mailhog:
    image: mailhog/mailhog:latest
    environment:
      - MH_STORAGE=maildir
    volumes:
      - ./mailhog/maildir:/maildir:rw,delegated
    ports:
      - "8025:8025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - php
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=sylius
      - PMA_PASSWORD=${MYSQL_PASSWORD:-nopassword}
    ports:
      - "8080:80"

volumes:
  mysql-data:
  public-media: