"https://{default}/":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: true
        # Cache configuration for different content types
        headers: ['Accept', 'Accept-Language']

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"
